- coresdk/src/coresdk/dataframe.cpp
- coresdk/src/coresdk/dataframe.h
- coresdk/src/test/unit_tests/unit_test_dataframe.cpp
Changes to allow updating column values and changes to remove non-public methods from the dataframe header
Changes made:
- **Renamed** "dataframe_validate_col" and "dataframe_validate_row" to "dataframe_validate_col_idx" and "dataframe_validate_row_idx"
- to better describe that the requested index is being validated and not the cell data
- **Moved** "dataframe_validate_col_idx" and "dataframe_validate_row_idx" out of the header files and into cpp files
- these methods are not part of the public API
- **Added** "dataframe_update_col" method to allow modifying the data in a column
- to simplify from needing delete and insert a column to achieve this
- **Test** cases added for "dataframe_update_col" method
- to validate that the method achieve user expectations
> feat: add update column to dataframe

- coresdk/src/coresdk/dataframe.cpp
- coresdk/src/coresdk/dataframe.h
- coresdk/src/test/test_dataframe.cpp
- coresdk/src/test/unit_tests/unit_test_dataframe.cpp
Changes made:
- **Added** compatibility with null types in existing methods
- **Added** dataframe column types
- **Added** unit tests for column types, null compatability and deleting columns/rows in skunit_tests
- **Added** demo with most dataframe methods in sktest
- **Added** documentation where it was missing
- **Removed** extra whitespace where present
> feat: add dataframe null type compatibility to existing methods

- coresdk/src/coresdk/collisions.cpp
Previous version does not check in sprite-sprite collision function, if both sprites are in AABB collision kind, only one at a time which S1 takes precedence first. Swingame source also lacks this check.
This adds an IF statement between checking for collision rectangle overlap and first AABB check. Immediately returns TRUE since after the first IF statement, they have to be intersecting collision rectangles already.
Discrepancy was noted by me approximately in May, when trying an external (to Splashkit library) "Collide" function in C#.
> Add check for both sprites in AABB collision kind for Sprite-Sprite collision function

- coresdk/src/coresdk/window_manager.cpp
- coresdk/src/test/test_sprites.cpp
reusing the bitmaps existing, two sprites set to AABB collision kind are placed within bounds to run sprite-collision. A/D move one of the sprite left or right for a set distance. Collision rectangles are drawn if sprite collision returns true (in black).
> Sprite Test alteration - AABB Sprite-Sprite check

- coresdk/src/coresdk/web_server.cpp
- coresdk/src/test/unit_tests/unit_test_web_server.cpp
Fixes [#129](https://github.com/splashkit/splashkit-core/issues/129)
Tested using the included unit tests.
> Fix uri splitting when a / isn't before args

- tools/scripts/install-win-libraries.sh
When the project is compiled from the projects folder, as per CONTRIBUTING.md and then the GPIO tests from `./sktest` are run it results in errors.
These errors are due to a typo in `raspi_gpio.cpp` and an error in the logic of `check_pi()` in `gpio_driver.cpp`.
`check_pi` return true only when `pigpio_start` has returned a negative value, which indicates an error. Thus, its use later on to in `sk_gpio_read` means that pin readings are only attempted on non-compatible boards.
Fixes [#167](https://github.com/splashkit/splashkit-core/issues/167)
`sktest` was rerun after the changes, and the tests behave as expected.
> Fix GPIO Tests

- coresdk/src/backend/graphics_driver.cpp
There were occasions when saving bitmaps, and restoring bitmaps (when all windows are destroyed then recreated) would cause them to be flipped vertically.
An `sk_drawing_surface` can have its internal bitmap stored either in textures or a surface, depending on if its 'drawable'. The code that handled reading from textures/renderers had a special case for Windows, that flipped the texture (or the coordinates being read) vertically. This was likely a workaround for a bug that used to be in SDL, but was [fixed](https://github.com/libsdl-org/SDL/issues/2182) a while ago, so this PR simply removes those special cases.
expected) - if any people using SplashKit relied on the textures being flipped (or worked around it), they will experience different behavior.
Tested using the following sample, …
> Fix erroneous flipping of renderers

- coresdk/src/backend/text_driver.cpp
`sk_text_size` uses `TTF_SizeText` internally to calculate the size of the text. This function is only expecting Latin-1 encoded text, and as such doesn't work properly when given most Unicode characters. This PR just replaces `TTF_SizeText` with `TTF_SizeUTF8`, which makes it take Unicode now instead, matching the rest of the `text_driver.cpp` functions.
The size returned from `sk_text_size` with various non English strings has been checked and shown to properly fit the returned text. Without the commit, the width returned is too long.
Can be tested with the following:
```c++
font fontA = load_font("font 1", "kochi-gothic-subst.ttf");
string testA = "Hello!";
draw_text(testA, COLOR_BLACK, fontA, 15, 0, 10);
draw_rectangle(COLOR_BLACK, 0, 10, text_width(testA, fontA, 15), …
```
> Fix text_driver returning wrong size for non Latin-1 characters

- coresdk/src/coresdk/triangle_geometry.cpp
- coresdk/src/test/unit_tests/unit_test_triangle.cpp
There's a typo in the logic of `triangle_rectangle_intersect()` for when the intersection point is on the right hand side of the triangle (when the base is parallel with the x axis) where the incorrect vertex of the rectangle is used to check for the intersection.
expected)
Tested using the included unit tests. Additionally tested with the example code given in the linked trello card.
> Fix triangle rectangle intersection

- coresdk/src/backend/gpio_driver.cpp
- coresdk/src/backend/gpio_driver.h
- coresdk/src/coresdk/raspi_gpio.cpp
- coresdk/src/coresdk/raspi_gpio.h
- coresdk/src/test/test_main.cpp
- coresdk/src/test/test_main.h
- coresdk/src/test/test_raspi_spi.cpp
This PR adds functions to open and close a connection through SPI, as well as transfer data between devices. This is a common communication protocol and allows us to connect with a wide variety of sensors. Included is a simple test to open a connection, transfer data, and then close.
For more information see tutorial 5 in [this pull request](https://github.com/thoth-tech/SplashKit-Tutorial/pull/45).
Included is a test for the basic functionality of the functions, furthermore they have been actively used to produce the tutorial mentioned above. Specifically, they have been used to communicate with the MCP3008 ADC to read a joysticks position. See linked tutorial for more information.
> feat(gpio): add spi protocol functions

- coresdk/src/coresdk/keyboard_input.cpp
- coresdk/src/test/test_input.cpp
Extended any_keys_pressed so that  holding down multiple keys and then releasing one will make any_key_pressed return true. Rather than trying to track this with a boolean any_keys_pressed() now reads the size of the keys down map. Also amended how  _keys_down map works. Previously a new key-value pair would be created when a key was pressed. When the key is released the boolean is set to false, but it does not appear that these false keys were ever actually used for anything. This would give an erroneous value for size as it it would return the number of unique keys that had ever been pressed since the program began running. Now the key is erased from the map when the keyboard key is released. The any_keys_pressed()  now just tests whether the size of_keys_down is non-zero, and returns a …
> Extend any_key_pressed() to handle multiple held keys

- coresdk/src/coresdk/circle_geometry.cpp
- coresdk/src/coresdk/vector_2d.cpp
- coresdk/src/coresdk/vector_2d.h
Fix typo in the splashkit website documentation.
I find where the typo located and then manage to change from "sqared" to "squared".
> fix typo documentation

- coresdk/src/coresdk/line_geometry.cpp
- coresdk/src/test/test_geometry.cpp
I attempted to use the closest_point_on_lines function in my circle_triangle_intersects function and found that it behaved strangely. Further investigation revealed two major bugs. First, despite `result` being initialised, it is never returned. Second, `min_dist` is initialised as `-1`, which means that the comparison `min_dist > dst` will always resolve to `false` as `dst` must be a positive number returned from `point_point_distance`. The special case when `lines.size() == 0` is handled correctly by returning `0,0` with `line_idx=0`, however I felt that an early return for this case would make the function easier to understand.
It is possible that the incorrect behavior of this function has lead to workarounds being used in projects. Therefore, I believe that this is a breaking change. …
> Fix bugs in closest_point_on_lines

- coresdk/src/coresdk/circle_geometry.cpp
- coresdk/src/coresdk/circle_geometry.h
- coresdk/src/test/test_geometry.cpp
There is no triangle-circle intersection test currently available in SplashKit, despite
being a useful test for game development.
I created two functions which will be expand the utility of the SplashKit library.
The first detects whether or not a circle and triangle are intersecting and returns
the Boolean result
The second has the functionality of the first but also supplies the closest point on the
triangle to the circle's center. This is achieved by passing a point_2d reference to the
function. Passing a value by reference to receive output may be complicated to
beginner programmers. Fortunately, the first function operates in a standard manner
and will be easily understandable.
expected)
I created a graphical test of my functions in the test_geometry.cpp file.
Four static triangles …
> added circle-triangle intersection functions

- coresdk/src/test/unit_tests/unit_test_bitmap.cpp
- coresdk/src/test/unit_tests/unit_test_music.cpp
- coresdk/src/test/unit_tests/unit_test_sound_effect.cpp
There is currently only two unit tests: JSON and text. There are many other processes which could be tested such as audio, images. I have created three unit tests which cover bitmaps, sound effects and music. They each perform exhaustive testing of the types including their loading and freeing.
expected)
Adding the new tests was achieved by running `cmake -G "Unix Makefiles" .` followed by `make` when in the `/splashkit-core/projects/cmake` directory. The tests deliberately cause warning messages to occur in the terminal when they attempt to load non-existent files.
> Add bitmap, sound effect and music unit tests

- coresdk/src/coresdk/basics.cpp
- coresdk/src/test/test_text.cpp
While creating unit tests, I identified a bug in the `replace_all` function which causes an infinite loop if the `substr` argument is an empty string. I added a check at the beginning of the function which detects if the sub-string is empty. If so, the input string `text` is returned.
There are multiple ways to handle this edge case. One is to throw an exception, another is to return an empty string. I believe the most logical response it to return the unaltered input string as it shows to the user that no action will be taken with an empty sub-string.
This is not a breaking change as the current behavior always results in a program crash.
I added an extra line of testing to `test_text.cpp` which uses an empty string as the `substr` argument. It runs as expected. In a separate pull …
> Fix bug in replace_all

- coresdk/src/test/unit_tests/unit_test_network.cpp
There are currently no unit tests for SplashKit's networking functions. I have created tests which cover the the creation of servers and connections, as well as the conversion functions.
Adding the new tests was achieved by running `cmake -G "Unix Makefiles" .` followed by `make` when in the `/splashkit-core/projects/cmake` directory.
> Add network unit tests

- coresdk/src/coresdk/random.cpp
- coresdk/src/test/test_graphics.cpp
The `rnd(int ubound)` and `rnd(int min, int max)` overloads of `rand` generate arithmetic exceptions when a divide by zero occurs through a modulo operator. `rnd(0)` will reliably generate the exception. When `min = max`, the divide by zero will occur in `rnd(int min, int max)` as `... % (max - min)` is used in the function.
I added calls to rnd(0) and rnd(10, 10) to `test_graphics.cpp` to test the edge cases. While it may seem out of place to use `rnd` in `test_graphics.cpp`, `#include "random.h"` was already present in the file with no associated references. Now the `#include` is justified.
> Fix bugs in rnd

- coresdk/src/test/unit_tests/unit_test_utilities.cpp
There are currently no unit tests for the functions listed under 'Utilities' in the SplashKit documentation. I have created exhaustive tests for each of these functions apart from `display_dialog` as it is generates purely graphical content and would be better suited for `sktests`.
In the process of creating the tests, I have identified issues with `replace_all`, `rnd` and `rnd(min, max)`. I can consistently cause an infinite loop in `replace_all`, and an unhanded exception in the two overloads of `rnd`. Keeping those tests in `skunit_tests` will cause it to fail. As a compromise, I have left the tests in place and commented them. My intention is to create separate pull requests to rectify the faulty functions. Once they are fixed, the tests can be uncommented.
Adding the new tests was …
> Add unit tests for utility functions

- coresdk/src/coresdk/collisions.cpp
- coresdk/src/coresdk/collisions.h
- coresdk/src/coresdk/images.cpp
- coresdk/src/coresdk/quad_geometry.cpp
- coresdk/src/coresdk/quad_geometry.h
- coresdk/src/test/test_geometry.cpp
- coresdk/src/test/test_sprites.cpp
There has been growing interest in using SplashKit to perform ray-tracing in both 2D and 3D environments. However, there is a lack of ray-based functions, particularly with detecting pixel-based collisions. I have added bitmap-ray and sprite-ray functions which will allow for more advanced ray-tracing, going beyond the primitive shapes.
This function constructs a quad around a passed-in segment. The width of the quad along the segment is also passed in as an argument.
I made use of a function which I previously developed and submitted in a previous PR: https://github.com/thoth-tech/splashkit-core/pull/83. Unlike in the previous PR, I did not include the 4 overloads in this PR.
`bitmap_ray_collision` calls `bitmap_bounding_circle` which contains a bug. The bug was detected and fixed in a …
> Add bitmap-ray and sprite-ray collision functions

- coresdk/src/coresdk/images.cpp
- coresdk/src/coresdk/point_geometry.cpp
- coresdk/src/coresdk/point_geometry.h
- coresdk/src/coresdk/sprites.cpp
- coresdk/src/coresdk/sprites.h
- coresdk/src/test/unit_tests/unit_test_bitmap.cpp
- coresdk/src/test/unit_tests/unit_test_geometry.cpp
- coresdk/src/test/unit_tests/unit_test_sprites.cpp
There are currently no unit tests for sprites. A comprehensive set of tests have been added which cover most sprite methods, with the exception of those which rely on a window. In the process of creating the tests, I discovered multiple bugs which have been also been rectified.
`_sprite_data` uses the `point_2d` and `velocity_2d` types for `position` and `velocity` respectively. `point_2d` and `velocity_2d` both use the `double` type. `sprite_x`, `sprite_y`, `sprite_set_x`, `sprite_set_y`, `sprite_dx`, `sprite_dy`, `sprite_set_dx`, and `sprite_set_dy` use the `float` type leading to unnecessary casting. Issues arise when the value stored in `point_2d` or `vector_2d`'s double is outside the range of `float`. The methods have been altered to accept and return `double`. …
> Add unit tests and fix bugs for sprites
